(1)
https://github.com/MiaHanzhangYuan/Lab3.git

(2)

In [1]:
import pandas as pd
import numpy as np
import requests
import os
import psycopg2
import zipfile
import io
from sqlalchemy import create_engine
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')

In [31]:
url ='https://databank.worldbank.org/data/download/ESG_CSV.zip'
r = requests.get(url)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

In [5]:
url = 'https://v-dem.net/media/datasets/V-Dem-CY-Core_csv_v13.zip'
r = requests.get(url)
print(r)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

<Response [200]>

In [4]:
wb = pd.read_csv("ESGData.csv")
country = pd.read_csv("ESGCountry.csv")

(c)

In [9]:
vdem = pd.read_csv("V-Dem-CY-Core-v13.csv")

In [10]:
vdem = vdem[['country_text_id', 'country_name', 'year', 'v2x_polyarchy']]

In [11]:
vdem.head(3).T

                      0       1       2
country_text_id     MEX     MEX     MEX
country_name     Mexico  Mexico  Mexico
year               1789    1790    1791
v2x_polyarchy     0.028   0.028   0.028

In [14]:
vdem = vdem.query("year>=1960 & year<=2021")

In [15]:
vdem = vdem.rename({'country_text_i':'country_code',
                   'country_name':'country_name_vdem',
                   'v2x_polyarchy':'democracy'}, axis=1)

(d)

In [15]:
country.head(3).T

,0,1,2
Country Code,AFG,AGO,ALB
Short Name,Afghanistan,Angola,Albania
Table Name,Afghanistan,Angola,Albania
Long Name,Islamic State of Afghanistan,People's Republic of Angola,Republic of Albania
2-alpha code,AF,AO,AL
Currency Unit,Afghan afghani,Angolan kwanza,Albanian lek
Special Notes,The reporting period for national accounts dat...,The World Bank systematically assesses the app...,NaN
Region,South Asia,Sub-Saharan Africa,Europe & Central Asia
Income Group,Low income,Lower middle income,Upper middle income
WB-2 code,AF,AO,AL
National accounts base year,2016,2002,Original chained constant price data are resca...
National accounts reference year,NaN,NaN,2010.0
SNA price valuation,Value added at basic prices (VAB),Value added at basic prices (VAB),Value added at basic prices (VAB)
Lending category,IDA,IBRD,IBRD
Other groups,HIPC,NaN,NaN
System of National Accounts,Country uses the 1993 System of National Accou...,Country uses the 1993 System of National Accou...,Country uses the 2008 System of National Accou...
Alternative conversion factor,NaN,NaN,NaN
PPP survey year,NaN,NaN,NaN
Balance of Payments Manual in use,BPM6,BPM6,BPM6
External debt Reporting status,Estimate,Actual,Actual
System of trade,General trade system,General trade system,Special trade system
Government Accounting concept,Consolidated central government,Budgetary central government,Consolidated central government
IMF data dissemination standard,Enhanced General Data Dissemination System (e-...,Enhanced General Data Dissemination System (e-...,Enhanced General Data Dissemination System (e-...
Latest population census,1979,2014,2020 (expected)
Latest household survey,"Demographic and Health Survey, 2015","Demographic and Health Survey, 2015/16","Demographic and Health Survey, 2017/18"
Source of most recent Income and expenditure data,"Integrated household survey (IHS), 2016/17","Integrated household survey (IHS), 2008/09",Living Standards Measurement Study Survey (LSM...
Vital registration complete,NaN,NaN,Yes
Latest agricultural census,NaN,NaN,2012
Latest industrial data,NaN,NaN,2013.0
Latest trade data,2018.0,2018.0,2018.0
Unnamed: 30,NaN,NaN,NaN

In [16]:
country = country[['Country Code', 'Table Name', 'Long Name', 'Currency Unit', 'Region', 'Income Group']]

In [19]:
country.columns = [x.lower() for x in country.columns]
country.columns = [x.replace(' ','_') for x in country.columns]
country.columns

Index(['country_code', 'table_name', 'long_name', 'currency_unit', 'region',
       'income_group'],
      dtype='object')

In [20]:
country = country.rename({'table_name':'country_name_wb'}, axis=1)
country

,country_code,country_name_wb,long_name,currency_unit,region,income_group
0,AFG,Afghanistan,Islamic State of Afghanistan,Afghan afghani,South Asia,Low income
1,AGO,Angola,People's Republic of Angola,Angolan kwanza,Sub-Saharan Africa,Lower middle income
2,ALB,Albania,Republic of Albania,Albanian lek,Europe & Central Asia,Upper middle income
3,AND,Andorra,Principality of Andorra,Euro,Europe & Central Asia,High income
4,ARB,Arab World,Arab World,NaN,NaN,NaN
...,...,...,...,...,...,...
234,WSM,Samoa,Samoa,Samoan tala,East Asia & Pacific,Lower middle income
235,YEM,"Yemen, Rep.",Republic of Yemen,Yemeni rial,Middle East & North Africa,Low income
236,ZAF,South Africa,Republic of South Africa,South African rand,Sub-Saharan Africa,Upper middle income
237,ZMB,Zambia,Republic of Zambia,New Zambian kwacha,Sub-Saharan Africa,Lower middle income
238,ZWE,Zimbabwe,Republic of Zimbabwe,Zimbabwean Dollar,Sub-Saharan Africa,Lower middle income

In [21]:
noncountries = ["Arab World", "Central Europe and the Baltics",
 "Caribbean small states",
 "East Asia & Pacific (excluding high income)",
 "Early-demographic dividend","East Asia & Pacific",
 "Europe & Central Asia (excluding high income)",
 "Europe & Central Asia", "Euro area",
 "European Union","Fragile and conflict affected situations",
 "High income",
 "Heavily indebted poor countries (HIPC)","IBRD only",
 "IDA & IBRD total",
 "IDA total","IDA blend","IDA only",
 "Latin America & Caribbean (excluding high income)",
 "Latin America & Caribbean",
 "Least developed countries: UN classification",
 "Low income","Lower middle income","Low & middle income",
 "Late-demographic dividend","Middle East & North Africa",
 "Middle income",
 "Middle East & North Africa (excluding high income)",
 "North America","OECD members",
 "Other small states","Pre-demographic dividend",
 "Pacific island small states",
 "Post-demographic dividend",
 "Sub-Saharan Africa (excluding high income)","Sub-Saharan Africa",
 "Small states","East Asia & Pacific (IDA & IBRD)",
 "Europe & Central Asia (IDA & IBRD)",
 "Latin America & Caribbean (IDA & IBRD)",
 "Middle East & North Africa (IDA & IBRD)","South Asia",
 "South Asia (IDA & IBRD)",
 "Sub-Saharan Africa (IDA & IBRD)",
 "Upper middle income", "World"]

In [22]:
country.query("country_name_wb not in @noncountries")

,country_code,country_name_wb,long_name,currency_unit,region,income_group
0,AFG,Afghanistan,Islamic State of Afghanistan,Afghan afghani,South Asia,Low income
1,AGO,Angola,People's Republic of Angola,Angolan kwanza,Sub-Saharan Africa,Lower middle income
2,ALB,Albania,Republic of Albania,Albanian lek,Europe & Central Asia,Upper middle income
3,AND,Andorra,Principality of Andorra,Euro,Europe & Central Asia,High income
5,ARE,United Arab Emirates,United Arab Emirates,U.A.E. dirham,Middle East & North Africa,High income
...,...,...,...,...,...,...
234,WSM,Samoa,Samoa,Samoan tala,East Asia & Pacific,Lower middle income
235,YEM,"Yemen, Rep.",Republic of Yemen,Yemeni rial,Middle East & North Africa,Low income
236,ZAF,South Africa,Republic of South Africa,South African rand,Sub-Saharan Africa,Upper middle income
237,ZMB,Zambia,Republic of Zambia,New Zambian kwacha,Sub-Saharan Africa,Lower middle income
238,ZWE,Zimbabwe,Republic of Zimbabwe,Zimbabwean Dollar,Sub-Saharan Africa,Lower middle income

(e)

In [26]:
wb = wb[['Country Code', 'Country Name', 'Indicator Code', wb.columns.str.startswith("19"), wb.columns.str.startswith("20")]]

TypeError: unhashable type: 'numpy.ndarray'

In [24]:
wb.head(3).T

,0,1,2
Country Name,Arab World,Arab World,Arab World
Country Code,ARB,ARB,ARB
Indicator Name,Access to clean fuels and technologies for coo...,Access to electricity (% of population),Adjusted savings: natural resources depletion ...
Indicator Code,EG.CFT.ACCS.ZS,EG.ELC.ACCS.ZS,NY.ADJ.DRES.GN.ZS
1960,NaN,NaN,NaN
...,...,...,...
2019,87.79874,90.352802,7.351742
2020,87.948264,90.63505,4.347213
2021,88.092536,90.845661,NaN
2022,NaN,NaN,NaN
Unnamed: 67,NaN,NaN,NaN

In [25]:
noncountries.remove('World')

In [ ]:
replace_map = {
 "AG.LND.AGRI.ZS": "agricultural_land",
 "AG.LND.FRST.ZS": "forest_area",
 "AG.PRD.FOOD.XD": "food_production_index",
 "CC.EST": "control_of_corruption",
 "EG.CFT.ACCS.ZS": "access_to_clean_fuels_and_technologies_for_cooking",
 "EG.EGY.PRIM.PP.KD": "energy_intensity_level_of_primary_energy",
 "EG.ELC.ACCS.ZS": "access_to_electricity",
 "EG.ELC.COAL.ZS": "electricity_production_from_coal_sources",
 "EG.ELC.RNEW.ZS": "renewable_electricity_output",
 "EG.FEC.RNEW.ZS": "renewable_energy_consumption",
 "EG.IMP.CONS.ZS": "energy_imports",
 "EG.USE.COMM.FO.ZS": "fossil_fuel_energy_consumption",
 "EG.USE.PCAP.KG.OE": "energy_use",
 "EN.ATM.CO2E.PC": "co2_emissions",
 "EN.ATM.METH.PC": "methane_emissions",
 "EN.ATM.NOXE.PC": "nitrous_oxide_emissions",
 "EN.ATM.PM25.MC.M3": "pm2_5_air_pollution",
 "EN.CLC.CDDY.XD": "cooling_degree_days",
 "EN.CLC.GHGR.MT.CE": "ghg_net_emissions",
 "EN.CLC.HEAT.XD": "heat_index_35",
 "EN.CLC.MDAT.ZS": "droughts",
 "EN.CLC.PRCP.XD": "maximum_5-day_rainfall",
 "EN.CLC.SPEI.XD": "mean_drought_index","EN.MAM.THRD.NO": "mammal_species",
 "EN.POP.DNST": "population_density",
 "ER.H2O.FWTL.ZS": "annual_freshwater_withdrawals",
 "ER.PTD.TOTL.ZS": "terrestrial_and_marine_protected_areas",
 "GB.XPD.RSDV.GD.ZS": "research_and_development_expenditure",
 "GE.EST": "government_effectiveness",
 "IC.BUS.EASE.XQ": "ease_of_doing_business_rank",
 "IC.LGL.CRED.XQ": "strength_of_legal_rights_index",
 "IP.JRN.ARTC.SC": "scientific_and_technical_journal_articles",
 "IP.PAT.RESD": "patent_applications",
 "IT.NET.USER.ZS": "individuals_using_the_internet",
 "NV.AGR.TOTL.ZS": "agriculture",
 "NY.ADJ.DFOR.GN.ZS": "net_forest_depletion",
 "NY.ADJ.DRES.GN.ZS": "natural_resources_depletion",
 "NY.GDP.MKTP.KD.ZG": "gdp_growth",
 "PV.EST": "political_stability_and_absence_of_violence",
 "RL.EST": "rule_of_law",
 "RQ.EST": "regulatory_quality",
 "SE.ADT.LITR.ZS": "literacy_rate",
 "SE.ENR.PRSC.FM.ZS": "gross_school_enrollment",
 "SE.PRM.ENRR": "primary_school_enrollment",
 "SE.XPD.TOTL.GB.ZS": "government_expenditure_on_education",
 "SG.GEN.PARL.ZS": "proportion_of_seats_held_by_women_in_national_parliamen",
 "SH.DTH.COMM.ZS": "cause_of_death",
 "SH.DYN.MORT": "mortality_rate",
 "SH.H2O.SMDW.ZS": "people_using_safely_managed_drinking_water_services",
 "SH.MED.BEDS.ZS": "hospital_beds",
 "SH.STA.OWAD.ZS": "prevalence_of_overweight",
 "SH.STA.SMSS.ZS": "people_using_safely_managed_sanitation_services",
 "SI.DST.FRST.20": "income_share_held_by_lowest_20pct",
 "SI.POV.GINI": "gini_index",
 "SI.POV.NAHC": "poverty_headcount_ratio_at_national_poverty_lines",
 "SI.SPR.PCAP.ZG": "annualized_average_growth_rate_in_per_capita_real_surve",
 "SL.TLF.0714.ZS": "children_in_employment",
 "SL.TLF.ACTI.ZS": "labor_force_participation_rate",
 "SL.TLF.CACT.FM.ZS": "ratio_of_female_to_male_labor_force_participation_ra",
 "SL.UEM.TOTL.ZS": "unemployment",
 "SM.POP.NETM": "net_migration",
 "SN.ITK.DEFC.ZS": "prevalence_of_undernourishment",
 "SP.DYN.LE00.IN": "life_expectancy_at_birth",
 "SP.DYN.TFRT.IN": "fertility_rate",
 "SP.POP.65UP.TO.ZS": "population_ages_65_and_above",
 "SP.UWT.TFRT": "unmet_need_for_contraception",
 "VA.EST": "voice_and_accountability",
 "EN.CLC.CSTP.ZS": "coastal_protection",
 "SD.ESR.PERF.XQ": "economic_and_social_rights_performance_score",
 "EN.CLC.HDDY.XD": "heating_degree_days",
 "EN.LND.LTMP.DC": "land_surface_temperature",
 "ER.H2O.FWST.ZS": "freshwater_withdrawal",
 "EN.H2O.BDYS.ZS": "water_quality",
 "AG.LND.FRLS.HA": "tree_cover_loss",
}